In [1]:
import torch
import zoib

In [2]:
zoib_fit = zoib.ZOIBeta(p=torch.tensor([.5]), 
               q=torch.tensor([.3]), 
               concentration1=torch.tensor([1.]), 
               concentration0=torch.tensor([1.]))

In [3]:
zoib_fit.log_prob(torch.tensor([0.])) 

tensor([-0.6931])

In [4]:
zoib_fit.log_prob(torch.tensor([1.]))

tensor([-1.8971])

In [5]:
zoib_fit.log_prob(torch.tensor([0.4]))

tensor([-1.0498])

In [6]:
zoib_fit.log_prob(torch.tensor([.9]))

tensor([-1.0498])

In [7]:
zoib_fit.log_prob(torch.tensor([.2]))

tensor([-1.0498])

In [8]:
# Test full loss
pred = torch.tensor([[0.5, 0.3, 1., 1.],[0.5, 0.3, 1., 1.], [0.5, 0.3, 1., 1.], [0.5, 0.3, 1., 1.], [0.5, 0.3, 1., 1.]])
true_y = torch.tensor([0., 1., 0.4, 0.9, 0.2])
log_probs = zoib.zoib_loss(
    pred,
    true_y,# Flatten to (batch_size*timesteps) X 1
    return_mean=False) # 1.
print(log_probs)

tensor(1.1479)
